// AUTO-GENERATED by scripts/compile-data.mjs from data/media.json5.
// Edit that file, not this one. Run `pnpm run compile-data`.

import type { LabelWriterMedia } from '../types.js';

export type MediaKey = 'RETURN_ADDRESS' | 'ADDRESS_STANDARD' | 'ADDRESS_LARGE' | 'SHIPPING_STANDARD' | 'SHIPPING_LARGE' | 'SHIPPING_4X6' | 'LEVER_ARCH' | 'FILE_FOLDER' | 'MULTI_PURPOSE_EXTRA_SMALL' | 'MULTI_PURPOSE_SQUARE' | 'MULTI_PURPOSE_SMALL' | 'MULTI_PURPOSE_MEDIUM' | 'MULTI_PURPOSE_LARGE' | 'MULTI_PURPOSE_VIDEO_TOP' | 'REMOVABLE' | 'SHELVING' | 'APPOINTMENT_CARD' | 'BOOK_SPINE' | 'BARCODE_DYMO_FILE' | 'NAME_BADGE' | 'NAME_BADGE_NON_ADHESIVE' | 'PRICE_TAG' | 'PRICE_TAG_2UP' | 'CONTINUOUS_57MM';

export const MEDIA = {
  RETURN_ADDRESS: {
    "id": "return-address",
    "name": "19×51mm Return Address",
    "category": "address",
    "widthMm": 19,
    "heightMm": 51,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 602,
    "skus": [
      "30330",
      "30578"
    ],
    "targetModels": [
      "lw"
    ]
  },
  ADDRESS_STANDARD: {
    "id": "address-standard",
    "name": "89×28mm Address",
    "category": "address",
    "widthMm": 28,
    "heightMm": 89,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "30251",
      "30252",
      "30254",
      "30320",
      "30340"
    ],
    "targetModels": [
      "lw"
    ]
  },
  ADDRESS_LARGE: {
    "id": "address-large",
    "name": "89×36mm Large Address",
    "category": "address",
    "widthMm": 36,
    "heightMm": 89,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "30321"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHIPPING_STANDARD: {
    "id": "shipping-standard",
    "name": "102×54mm Shipping",
    "category": "shipping",
    "widthMm": 54,
    "heightMm": 102,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1205,
    "skus": [
      "30323"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHIPPING_LARGE: {
    "id": "shipping-large",
    "name": "102×59mm Large Shipping",
    "category": "shipping",
    "widthMm": 59,
    "heightMm": 102,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1205,
    "skus": [
      "30256",
      "1763982",
      "1933088"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHIPPING_4X6: {
    "id": "shipping-4x6",
    "name": "152×102mm Extra Large Shipping (4×6)",
    "category": "shipping",
    "widthMm": 102,
    "heightMm": 152,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1795,
    "skus": [
      "1744907",
      "1933086"
    ],
    "targetModels": [
      "lw-wide"
    ]
  },
  LEVER_ARCH: {
    "id": "lever-arch",
    "name": "190×59mm Lever Arch / Confirmation",
    "category": "shipping",
    "widthMm": 59,
    "heightMm": 190,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 2244,
    "skus": [
      "1933087"
    ],
    "targetModels": [
      "lw"
    ]
  },
  FILE_FOLDER: {
    "id": "file-folder",
    "name": "87×14mm File Folder",
    "category": "file-folder",
    "widthMm": 14,
    "heightMm": 87,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1027,
    "skus": [
      "30327"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_EXTRA_SMALL: {
    "id": "multi-purpose-extra-small",
    "name": "25×13mm Extra Small (2-up)",
    "category": "multi-purpose",
    "widthMm": 13,
    "heightMm": 25,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 295,
    "skus": [
      "30333"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_SQUARE: {
    "id": "multi-purpose-square",
    "name": "25×25mm Square",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 25,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 295,
    "skus": [
      "30332",
      "1933083"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_SMALL: {
    "id": "multi-purpose-small",
    "name": "54×25mm Small",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 54,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 638,
    "skus": [
      "30336",
      "1976411"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_MEDIUM: {
    "id": "multi-purpose-medium",
    "name": "57×32mm Medium",
    "category": "multi-purpose",
    "widthMm": 32,
    "heightMm": 57,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 673,
    "skus": [
      "30334",
      "1933084"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_LARGE: {
    "id": "multi-purpose-large",
    "name": "70×54mm Large",
    "category": "multi-purpose",
    "widthMm": 54,
    "heightMm": 70,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 827,
    "skus": [
      "30324"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_VIDEO_TOP: {
    "id": "multi-purpose-video-top",
    "name": "79×46mm Video Top",
    "category": "multi-purpose",
    "widthMm": 46,
    "heightMm": 79,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 933,
    "skus": [
      "30326"
    ],
    "targetModels": [
      "lw"
    ]
  },
  REMOVABLE: {
    "id": "removable",
    "name": "59×51mm Removable",
    "category": "multi-purpose",
    "widthMm": 51,
    "heightMm": 59,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 697,
    "skus": [
      "30370"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHELVING: {
    "id": "shelving",
    "name": "89×25mm Shelving",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 89,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "1933081"
    ],
    "targetModels": [
      "lw"
    ]
  },
  APPOINTMENT_CARD: {
    "id": "appointment-card",
    "name": "89×51mm Appointment / Business Card",
    "category": "multi-purpose",
    "widthMm": 51,
    "heightMm": 89,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "30374"
    ],
    "targetModels": [
      "lw"
    ]
  },
  BOOK_SPINE: {
    "id": "book-spine",
    "name": "38×25mm Book Spine",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 38,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 449,
    "skus": [
      "30347"
    ],
    "targetModels": [
      "lw"
    ]
  },
  BARCODE_DYMO_FILE: {
    "id": "barcode-dymo-file",
    "name": "64×19mm Barcode / DYMO File",
    "category": "barcode",
    "widthMm": 19,
    "heightMm": 64,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 756,
    "skus": [
      "1933085"
    ],
    "targetModels": [
      "lw"
    ]
  },
  NAME_BADGE: {
    "id": "name-badge",
    "name": "102×57mm Name Badge",
    "category": "name-badge",
    "widthMm": 57,
    "heightMm": 102,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1205,
    "skus": [
      "30857",
      "30911"
    ],
    "targetModels": [
      "lw"
    ]
  },
  NAME_BADGE_NON_ADHESIVE: {
    "id": "name-badge-non-adhesive",
    "name": "106×62mm Name Badge Non-Adhesive",
    "category": "name-badge",
    "widthMm": 62,
    "heightMm": 106,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1252,
    "skus": [
      "30856"
    ],
    "targetModels": [
      "lw"
    ]
  },
  PRICE_TAG: {
    "id": "price-tag",
    "name": "24×22mm Price Tag",
    "category": "price-tag",
    "widthMm": 24,
    "heightMm": 22,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 260,
    "skus": [
      "30373"
    ],
    "targetModels": [
      "lw"
    ]
  },
  PRICE_TAG_2UP: {
    "id": "price-tag-2up",
    "name": "19×10mm Price Tag (2-up)",
    "category": "price-tag",
    "widthMm": 10,
    "heightMm": 19,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 224,
    "skus": [
      "30299"
    ],
    "targetModels": [
      "lw"
    ]
  },
  CONTINUOUS_57MM: {
    "id": "continuous-57",
    "name": "57mm Continuous Non-Adhesive",
    "category": "continuous",
    "widthMm": 57,
    "type": "continuous",
    "skus": [
      "30270"
    ],
    "targetModels": [
      "lw"
    ]
  },
} as const satisfies Record<MediaKey, LabelWriterMedia>;
