// AUTO-GENERATED by scripts/compile-data.mjs from data/media.json5.
// Edit that file, not this one. Run `pnpm run compile-data`.

import type { LabelWriterAnyMedia } from '../types.js';

export type MediaKey = 'RETURN_ADDRESS' | 'ADDRESS_STANDARD' | 'ADDRESS_LARGE' | 'SHIPPING_STANDARD' | 'SHIPPING_LARGE' | 'SHIPPING_4X6' | 'LEVER_ARCH' | 'FILE_FOLDER' | 'MULTI_PURPOSE_EXTRA_SMALL' | 'MULTI_PURPOSE_SQUARE' | 'MULTI_PURPOSE_SMALL' | 'MULTI_PURPOSE_MEDIUM' | 'MULTI_PURPOSE_LARGE' | 'MULTI_PURPOSE_VIDEO_TOP' | 'REMOVABLE' | 'SHELVING' | 'APPOINTMENT_CARD' | 'BOOK_SPINE' | 'BARCODE_DYMO_FILE' | 'NAME_BADGE' | 'NAME_BADGE_NON_ADHESIVE' | 'PRICE_TAG' | 'PRICE_TAG_2UP' | 'CONTINUOUS_57MM' | 'STANDARD_BLACK_ON_WHITE_6' | 'STANDARD_BLACK_ON_CLEAR_9' | 'STANDARD_BLACK_ON_WHITE_9' | 'STANDARD_BLACK_ON_WHITE_12' | 'STANDARD_BLACK_ON_CLEAR_12' | 'STANDARD_BLACK_ON_YELLOW_12' | 'STANDARD_BLACK_ON_BLUE_12' | 'STANDARD_BLACK_ON_GREEN_12' | 'STANDARD_BLACK_ON_RED_12' | 'STANDARD_WHITE_ON_CLEAR_12' | 'STANDARD_WHITE_ON_BLACK_12' | 'STANDARD_BLUE_ON_WHITE_12' | 'STANDARD_RED_ON_WHITE_12' | 'STANDARD_BLACK_ON_WHITE_19' | 'STANDARD_BLACK_ON_CLEAR_19' | 'STANDARD_BLACK_ON_WHITE_24' | 'STANDARD_BLACK_ON_YELLOW_24' | 'PERMANENT_BLACK_ON_WHITE_12' | 'FLEXIBLE_BLACK_ON_WHITE_12' | 'DURABLE_BLACK_ON_WHITE_12' | 'DURABLE_WHITE_ON_BLACK_12' | 'DURABLE_WHITE_ON_RED_12' | 'DURABLE_BLACK_ON_ORANGE_12';

export const MEDIA = {
  RETURN_ADDRESS: {
    "id": "return-address",
    "name": "19×51mm Return Address",
    "category": "address",
    "widthMm": 19,
    "heightMm": 51,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 602,
    "skus": [
      "30330",
      "30578"
    ],
    "targetModels": [
      "lw"
    ]
  },
  ADDRESS_STANDARD: {
    "id": "address-standard",
    "name": "89×28mm Address",
    "category": "address",
    "widthMm": 28,
    "heightMm": 89,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "30251",
      "30252",
      "30254",
      "30320",
      "30340"
    ],
    "targetModels": [
      "lw"
    ]
  },
  ADDRESS_LARGE: {
    "id": "address-large",
    "name": "89×36mm Large Address",
    "category": "address",
    "widthMm": 36,
    "heightMm": 89,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "30321"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHIPPING_STANDARD: {
    "id": "shipping-standard",
    "name": "102×54mm Shipping",
    "category": "shipping",
    "widthMm": 54,
    "heightMm": 102,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1205,
    "skus": [
      "30323"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHIPPING_LARGE: {
    "id": "shipping-large",
    "name": "102×59mm Large Shipping",
    "category": "shipping",
    "widthMm": 59,
    "heightMm": 102,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1205,
    "skus": [
      "30256",
      "1763982",
      "1933088"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHIPPING_4X6: {
    "id": "shipping-4x6",
    "name": "152×102mm Extra Large Shipping (4×6)",
    "category": "shipping",
    "widthMm": 102,
    "heightMm": 152,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1795,
    "skus": [
      "1744907",
      "1933086"
    ],
    "targetModels": [
      "lw-wide"
    ]
  },
  LEVER_ARCH: {
    "id": "lever-arch",
    "name": "190×59mm Lever Arch / Confirmation",
    "category": "shipping",
    "widthMm": 59,
    "heightMm": 190,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 2244,
    "skus": [
      "1933087"
    ],
    "targetModels": [
      "lw"
    ]
  },
  FILE_FOLDER: {
    "id": "file-folder",
    "name": "87×14mm File Folder",
    "category": "file-folder",
    "widthMm": 14,
    "heightMm": 87,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1027,
    "skus": [
      "30327"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_EXTRA_SMALL: {
    "id": "multi-purpose-extra-small",
    "name": "25×13mm Extra Small (2-up)",
    "category": "multi-purpose",
    "widthMm": 13,
    "heightMm": 25,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 295,
    "skus": [
      "30333"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_SQUARE: {
    "id": "multi-purpose-square",
    "name": "25×25mm Square",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 25,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 295,
    "skus": [
      "30332",
      "1933083"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_SMALL: {
    "id": "multi-purpose-small",
    "name": "54×25mm Small",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 54,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 638,
    "skus": [
      "30336",
      "1976411"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_MEDIUM: {
    "id": "multi-purpose-medium",
    "name": "57×32mm Medium",
    "category": "multi-purpose",
    "widthMm": 32,
    "heightMm": 57,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 673,
    "skus": [
      "30334",
      "1933084"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_LARGE: {
    "id": "multi-purpose-large",
    "name": "70×54mm Large",
    "category": "multi-purpose",
    "widthMm": 54,
    "heightMm": 70,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 827,
    "skus": [
      "30324"
    ],
    "targetModels": [
      "lw"
    ]
  },
  MULTI_PURPOSE_VIDEO_TOP: {
    "id": "multi-purpose-video-top",
    "name": "79×46mm Video Top",
    "category": "multi-purpose",
    "widthMm": 46,
    "heightMm": 79,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 933,
    "skus": [
      "30326"
    ],
    "targetModels": [
      "lw"
    ]
  },
  REMOVABLE: {
    "id": "removable",
    "name": "59×51mm Removable",
    "category": "multi-purpose",
    "widthMm": 51,
    "heightMm": 59,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 697,
    "skus": [
      "30370"
    ],
    "targetModels": [
      "lw"
    ]
  },
  SHELVING: {
    "id": "shelving",
    "name": "89×25mm Shelving",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 89,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "1933081"
    ],
    "targetModels": [
      "lw"
    ]
  },
  APPOINTMENT_CARD: {
    "id": "appointment-card",
    "name": "89×51mm Appointment / Business Card",
    "category": "multi-purpose",
    "widthMm": 51,
    "heightMm": 89,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 1051,
    "skus": [
      "30374"
    ],
    "targetModels": [
      "lw"
    ]
  },
  BOOK_SPINE: {
    "id": "book-spine",
    "name": "38×25mm Book Spine",
    "category": "multi-purpose",
    "widthMm": 25,
    "heightMm": 38,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 449,
    "skus": [
      "30347"
    ],
    "targetModels": [
      "lw"
    ]
  },
  BARCODE_DYMO_FILE: {
    "id": "barcode-dymo-file",
    "name": "64×19mm Barcode / DYMO File",
    "category": "barcode",
    "widthMm": 19,
    "heightMm": 64,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 756,
    "skus": [
      "1933085"
    ],
    "targetModels": [
      "lw"
    ]
  },
  NAME_BADGE: {
    "id": "name-badge",
    "name": "102×57mm Name Badge",
    "category": "name-badge",
    "widthMm": 57,
    "heightMm": 102,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1205,
    "skus": [
      "30857",
      "30911"
    ],
    "targetModels": [
      "lw"
    ]
  },
  NAME_BADGE_NON_ADHESIVE: {
    "id": "name-badge-non-adhesive",
    "name": "106×62mm Name Badge Non-Adhesive",
    "category": "name-badge",
    "widthMm": 62,
    "heightMm": 106,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 1252,
    "skus": [
      "30856"
    ],
    "targetModels": [
      "lw"
    ]
  },
  PRICE_TAG: {
    "id": "price-tag",
    "name": "24×22mm Price Tag",
    "category": "price-tag",
    "widthMm": 24,
    "heightMm": 22,
    "type": "die-cut",
    "cornerRadiusMm": 3,
    "lengthDots": 260,
    "skus": [
      "30373"
    ],
    "targetModels": [
      "lw"
    ]
  },
  PRICE_TAG_2UP: {
    "id": "price-tag-2up",
    "name": "19×10mm Price Tag (2-up)",
    "category": "price-tag",
    "widthMm": 10,
    "heightMm": 19,
    "type": "die-cut",
    "defaultOrientation": "horizontal",
    "cornerRadiusMm": 3,
    "lengthDots": 224,
    "skus": [
      "30299"
    ],
    "targetModels": [
      "lw"
    ]
  },
  CONTINUOUS_57MM: {
    "id": "continuous-57",
    "name": "57mm Continuous Non-Adhesive",
    "category": "continuous",
    "widthMm": 57,
    "type": "continuous",
    "skus": [
      "30270"
    ],
    "targetModels": [
      "lw"
    ]
  },
  STANDARD_BLACK_ON_WHITE_6: {
    "id": "d1-standard-bw-6",
    "name": "6mm Black on White",
    "type": "tape",
    "widthMm": 6,
    "material": "standard",
    "background": "white",
    "text": "black",
    "skus": [
      "43613",
      "S0720780"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 6,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_CLEAR_9: {
    "id": "d1-standard-bc-9",
    "name": "9mm Black on Clear",
    "type": "tape",
    "widthMm": 9,
    "material": "standard",
    "background": "clear",
    "text": "black",
    "skus": [
      "40910",
      "S0720670"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 9,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_WHITE_9: {
    "id": "d1-standard-bw-9",
    "name": "9mm Black on White",
    "type": "tape",
    "widthMm": 9,
    "material": "standard",
    "background": "white",
    "text": "black",
    "skus": [
      "41913"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 9,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_WHITE_12: {
    "id": "d1-standard-bw-12",
    "name": "12mm Black on White",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "white",
    "text": "black",
    "skus": [
      "45013"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_CLEAR_12: {
    "id": "d1-standard-bc-12",
    "name": "12mm Black on Clear",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "clear",
    "text": "black",
    "skus": [
      "45010"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_YELLOW_12: {
    "id": "d1-standard-by-12",
    "name": "12mm Black on Yellow",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "yellow",
    "text": "black",
    "skus": [
      "45018"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 4
  },
  STANDARD_BLACK_ON_BLUE_12: {
    "id": "d1-standard-bbl-12",
    "name": "12mm Black on Blue",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "blue",
    "text": "black",
    "skus": [
      "45016",
      "S0720560"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 1
  },
  STANDARD_BLACK_ON_GREEN_12: {
    "id": "d1-standard-bg-12",
    "name": "12mm Black on Green",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "green",
    "text": "black",
    "skus": [
      "45019",
      "S0720590"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 6
  },
  STANDARD_BLACK_ON_RED_12: {
    "id": "d1-standard-br-12",
    "name": "12mm Black on Red",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "red",
    "text": "black",
    "skus": [
      "45017",
      "S0720570"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 2
  },
  STANDARD_WHITE_ON_CLEAR_12: {
    "id": "d1-standard-wc-12",
    "name": "12mm White on Clear",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "clear",
    "text": "white",
    "skus": [
      "45020",
      "S0720600"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 9
  },
  STANDARD_WHITE_ON_BLACK_12: {
    "id": "d1-standard-wbk-12",
    "name": "12mm White on Black",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "black",
    "text": "white",
    "skus": [
      "45021",
      "S0720610"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 10
  },
  STANDARD_BLUE_ON_WHITE_12: {
    "id": "d1-standard-blw-12",
    "name": "12mm Blue on White",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "white",
    "text": "blue",
    "skus": [
      "45014"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 11
  },
  STANDARD_RED_ON_WHITE_12: {
    "id": "d1-standard-rw-12",
    "name": "12mm Red on White",
    "type": "tape",
    "widthMm": 12,
    "material": "standard",
    "background": "white",
    "text": "red",
    "skus": [
      "45015",
      "S0720550"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 12
  },
  STANDARD_BLACK_ON_WHITE_19: {
    "id": "d1-standard-bw-19",
    "name": "19mm Black on White",
    "type": "tape",
    "widthMm": 19,
    "material": "standard",
    "background": "white",
    "text": "black",
    "skus": [
      "45800"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 19,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_CLEAR_19: {
    "id": "d1-standard-bc-19",
    "name": "19mm Black on Clear",
    "type": "tape",
    "widthMm": 19,
    "material": "standard",
    "background": "clear",
    "text": "black",
    "skus": [
      "45803",
      "S0720820"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 19,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_WHITE_24: {
    "id": "d1-standard-bw-24",
    "name": "24mm Black on White",
    "type": "tape",
    "widthMm": 24,
    "material": "standard",
    "background": "white",
    "text": "black",
    "skus": [
      "53713",
      "S0720930"
    ],
    "targetModels": [
      "d1-wide"
    ],
    "category": "cartridge",
    "tapeWidthMm": 24,
    "tapeColour": 0
  },
  STANDARD_BLACK_ON_YELLOW_24: {
    "id": "d1-standard-by-24",
    "name": "24mm Black on Yellow",
    "type": "tape",
    "widthMm": 24,
    "material": "standard",
    "background": "yellow",
    "text": "black",
    "skus": [
      "53718",
      "S0720980"
    ],
    "targetModels": [
      "d1-wide"
    ],
    "category": "cartridge",
    "tapeWidthMm": 24,
    "tapeColour": 4
  },
  PERMANENT_BLACK_ON_WHITE_12: {
    "id": "d1-permanent-bw-12",
    "name": "12mm Permanent Black on White",
    "type": "tape",
    "widthMm": 12,
    "material": "permanent-polyester",
    "background": "white",
    "text": "black",
    "skus": [
      "16955"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
  FLEXIBLE_BLACK_ON_WHITE_12: {
    "id": "d1-flexible-bw-12",
    "name": "12mm Flexible Black on White",
    "type": "tape",
    "widthMm": 12,
    "material": "flexible-nylon",
    "background": "white",
    "text": "black",
    "skus": [
      "16953",
      "S0718040"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
  DURABLE_BLACK_ON_WHITE_12: {
    "id": "d1-durable-bw-12",
    "name": "12mm Durable Black on White",
    "type": "tape",
    "widthMm": 12,
    "material": "durable",
    "background": "white",
    "text": "black",
    "skus": [
      "1978364"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
  DURABLE_WHITE_ON_BLACK_12: {
    "id": "d1-durable-wbk-12",
    "name": "12mm Durable White on Black",
    "type": "tape",
    "widthMm": 12,
    "material": "durable",
    "background": "black",
    "text": "white",
    "skus": [
      "1978365"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 10
  },
  DURABLE_WHITE_ON_RED_12: {
    "id": "d1-durable-wr-12",
    "name": "12mm Durable White on Red",
    "type": "tape",
    "widthMm": 12,
    "material": "durable",
    "background": "red",
    "text": "white",
    "skus": [
      "1978366"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
  DURABLE_BLACK_ON_ORANGE_12: {
    "id": "d1-durable-bo-12",
    "name": "12mm Durable Black on Orange",
    "type": "tape",
    "widthMm": 12,
    "material": "durable",
    "background": "orange",
    "text": "black",
    "skus": [
      "1978367"
    ],
    "targetModels": [
      "d1"
    ],
    "category": "cartridge",
    "tapeWidthMm": 12,
    "tapeColour": 0
  },
} as const satisfies Record<MediaKey, LabelWriterAnyMedia>;
