import type { LabelWriterDevice } from './types.js';

export const DEVICES = {
  LW_400: {
    name: 'LabelWriter 400',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x0019,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_400_TURBO: {
    name: 'LabelWriter 400 Turbo',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x0023,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_450: {
    name: 'LabelWriter 450',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x0020,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_450_TURBO: {
    name: 'LabelWriter 450 Turbo',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x002a,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_450_TWIN_TURBO: {
    name: 'LabelWriter 450 Twin Turbo',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x002b,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_450_DUO: {
    name: 'LabelWriter 450 Duo',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x002c,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_4XL: {
    name: 'LabelWriter 4XL',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x0025,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'none',
    nfcLock: false,
  },
  LW_WIRELESS: {
    name: 'LabelWriter Wireless',
    family: 'labelwriter',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x0922,
    pid: 0x0031,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '450',
    network: 'wifi',
    nfcLock: false,
  },
  LW_550: {
    name: 'LabelWriter 550',
    family: 'labelwriter',
    transports: ['usb', 'webusb'],
    vid: 0x0922,
    pid: 0x0052,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '550',
    network: 'none',
    nfcLock: true,
  },
  LW_550_TURBO: {
    name: 'LabelWriter 550 Turbo',
    family: 'labelwriter',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x0922,
    pid: 0x0053,
    headDots: 672,
    bytesPerRow: 84,
    protocol: '550',
    network: 'wired',
    nfcLock: true,
  },
  LW_5XL: {
    name: 'LabelWriter 5XL',
    family: 'labelwriter',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x0922,
    pid: 0x0054,
    headDots: 1248,
    bytesPerRow: 156,
    protocol: '550',
    network: 'wired',
    nfcLock: true,
  },
} as const satisfies Record<string, LabelWriterDevice>;

export function findDevice(vid: number, pid: number): LabelWriterDevice | undefined {
  return Object.values(DEVICES).find(d => d.vid === vid && d.pid === pid);
}
